const allAlbums = [
    {
        id: crypto.randomUUID(),
        name: "ASTROWORLD",
        genre: "rap",
        albumID: "41GuZcammIkupMPKH2OJ6I",
        hottest: false,
        price: 45.99,
    },
    {
        id: crypto.randomUUID(),
        name: "Graduation",
        genre: "rap",
        albumID: "4SZko61aMnmgvNhfhgTuD3",
        hottest: true,
        price: 65.99,
    },
    {
        id: crypto.randomUUID(),
        name: "HARDSTONE PSYCHO",
        genre: "rap",
        albumID: "55S2SOsWCYekWJtJ8LwVqV",
        hottest: true,
        price: 55.99,
    },
    {
        id: crypto.randomUUID(),
        name: "UTOPIA",
        genre: "rap",
        albumID: "18NOKLkZETa4sWwLMIm0UZ",
        hottest: true,
        price: 51.99,
    },
    {
        id: crypto.randomUUID(),
        name: "Scorpion",
        genre: "r&b",
        albumID: "1ATL5GLyefJaxhQzSPVrLX",
        hottest: false,
        price: 42.99,
    },
    {
        id: crypto.randomUUID(),
        name: "The Best of Sade",
        genre: "r&b",
        albumID: "3uSWaQxJAdm5MWKQkQJNoK",
        hottest: false,
        price: 43.99,
    },
    {
        id: crypto.randomUUID(),
        name: "Blonde",
        genre: "r&b",
        albumID: "3mH6qwIy9crq0I9YQbOuDf",
        hottest: false,
        price: 150.99,
    },
    {
        id: crypto.randomUUID(),
        name: "The Miseducation of Lauryn Hill",
        genre: "r&b",
        albumID: "1BZoqf8Zje5nGdwZhOjAtD",
        hottest: false,
        price: 44.99,
    },
    {
        id: crypto.randomUUID(),
        name: "DeBÍ TiRAR MáS FOToS",
        genre: "latin",
        albumID: "5K79FLRUCSysQnVESLcTdb",
        hottest: true,
        price: 44.99,
    },
    {
        id: crypto.randomUUID(),
        name: "Un Verano Sin Ti",
        genre: "latin",
        albumID: "3RQQmkQEvNCY4prGKE6oc5",
        hottest: true,
        price: 55.99,
    },
    {
        id: crypto.randomUUID(),
        name: "Cosa Nuestra",
        genre: "latin",
        albumID: "0aX0UXrHG2ceYIxTQcqJdA",
        hottest: true,
        price: 66.99,
    },
    {
        id: crypto.randomUUID(),
        name: "GÉNESIS",
        genre: "latin",
        albumID: "4jox3ip1I39DFC2B7R5qLH",
        hottest: true,
        price: 40.99,
    },
    {
        id: crypto.randomUUID(),
        name: "Hurry Up Tomorrow",
        genre: "pop",
        albumID: "3OxfaVgvTxUTy7276t7SPU",
        hottest: true,
        price: 33.99,
    },
    {
        id: crypto.randomUUID(),
        name: "Doo-Wops & Hooligans",
        genre: "pop",
        albumID: "1uyf3l2d4XYwiEqAb7t7fX",
        hottest: false,
        price: 39.99,
    }, 
    {
        id: crypto.randomUUID(),
        name: "Thriller",
        genre: "pop",
        albumID: "2ANVost0y2y52ema1E9xAZ",
        hottest: false,
        price: 41.99,
    },
    {
        id: crypto.randomUUID(),
        name: "Loud",
        genre: "pop",
        albumID: "35dJsQDEr549O5DTFUy3uM",
        hottest: false,
        price: 39.99,
    },
]

export default allAlbums;